# Generated by Django 2.1.1 on 2018-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0002_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
