# Generated by Django 2.1.1 on 2018-10-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0004_auto_20181003_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='proof_read',
            new_name='needs_proofreading',
        ),
    ]
