# Generated by Django 2.1.1 on 2018-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0005_auto_20181004_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
