# Generated by Django 2.1.1 on 2018-10-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0008_auto_20181015_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(null=True, to='view_content.Category'),
        ),
    ]
