# Generated by Django 2.1.1 on 2018-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0011_auto_20181016_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
    ]
