# Generated by Django 2.1.1 on 2018-10-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0012_post_needs_approval'),
        ('view_content', '0012_post_saved_users'),
    ]

    operations = [
    ]
