# Generated by Django 2.1.1 on 2018-11-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0012_auto_20181106_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolerequest',
            unique_together=set(),
        ),
    ]
