# Generated by Django 2.1.1 on 2018-10-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0013_merge_20181030_1644'),
        ('view_content', '0012_auto_20181028_1629'),
    ]

    operations = [
    ]
