# Generated by Django 2.1.1 on 2018-11-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0014_merge_20181031_1435'),
        ('view_content', '0013_auto_20181106_1534'),
    ]

    operations = [
    ]
